### ISSUE TITLE
/issues 레이블 추가?

### ISSUE THREAD

**Issue by mozodev** [parti-xyz/parti-intro#3]
몇 가지 레이블 help wanted(도와주세요), need review(검토가 필요해요!) session (이 이슈는 세션으로 진행한다) 뭐 이런걸 시범적으로 사용해보고 있습니다.
레이블도 표시해보겠습니다.

**Comment by dalikim** [comment]
pair with me 레이블은 어떨까요? 페어하고 싶다고.

**Comment by mozodev** [comment]
https://github.com/parti-xyz/parti-intro/commit/a2cf8f862542f0b857a8fa85aace5ab7ec15f40b
